#!/bin/bash

. /opt/IBM/ace/server/bin/mqsiprofile

> /home/scripts/Rohit_PORT/BROKER_PORT.txt
>/home/scripts/BROKERLIST.txt
> /home/scripts/Rohit_PORT/FILE_NAME_PORT

# Get the IP address
IP_ADDR=$(hostname -i)

for i in `ls /var/mqsi/components/`; do for j in `ls /var/mqsi/components/$i/servers/`; do echo "$i:$j";done  ; done  >> /home/scripts/BROKERLIST.txt

for i in `cat /home/scripts/BROKERLIST.txt  |grep -i HEART_BEAT | grep -i isolator  | cut -d ":" -f2`
do
BK=$i

PORT=$( mqsireportproperties HEART_BEAT -e $i  -o HTTPConnector -r  | grep -i ListenerPort | cut -d "'" -f2 | sort -u )

chk=`sh /home/scripts/Rohit_PORT/CHK4D.sh ${PORT}`

if [ "${chk}" == "1" ]
then
        echo "${IP_ADDR}:${i}:${PORT}" >> /home/scripts/Rohit_PORT/BROKER_PORT.txt
else
        PORT=`cat /var/mqsi/components/HEART_BEAT/servers/$i/server.conf.yaml  | grep -i HTTPConnector: -A5 | grep -i "ListenerPort" | cut -d ":" -f2 | awk '{print $1}'`
        chk=`sh /home/scripts/Rohit_PORT/CHK4D.sh ${PORT}`
        if [ "${chk}" == "1" ]
                then
                        echo "${IP_ADDR}:${i}:${PORT}" >> /home/scripts/Rohit_PORT/BROKER_PORT.txt
                else
                         PORT=`cat  /var/mqsi/components/HEART_BEAT/servers/$i/overrides/server.conf.yaml  | grep -i  HTTPConnector: -A2`
                         if [ "${chk}" == "1" ]
                                then
                                        echo "${IP_ADDR}:${i}:${PORT}" >> /home/scripts/Rohit_PORT/BROKER_PORT.txt
                                else
                                        echo "${IP_ADDR}:${i}:9980" >> /home/scripts/Rohit_PORT/BROKER_PORT.txt
                         fi
        fi
fi
done
#---------------------------------------------------ISOLATOREND------------------------------
for i in `cat /home/scripts/BROKERLIST.txt | cut -d ":" -f1 | sort -u | grep -v CACHE  | grep -v HEART_BEAT`
do
BK=$i
PORT=$(mqsireportproperties $i  -b httplistener -o HTTPConnector -a  | grep -i Listenerport | cut -d "'" -f2)
if [ "${PORT}" == "" ]
then
  echo ;
else
echo "${IP_ADDR}:${i}:${PORT}" >> /home/scripts/Rohit_PORT/BROKER_PORT.txt
fi
done

chmod 777 /home/scripts/Rohit_PORT/BROKER_PORT.txt;

sh /home/scripts/Rohit_PORT/GET_UDPPORT.sh
cat /home/scripts/Rohit_PORT/BROKER_PORT.txt  > /home/scripts/Rohit_PORT/`hostname -i`_Port_Data.json

echo "/home/scripts/Rohit_PORT/`hostname -i`_Port_Data.json" > /home/scripts/Rohit_PORT/FILE_NAME_PORT

timeout 2s    echo " put `cat /home/scripts/Rohit_PORT/FILE_NAME_PORT`  /home/scripts/Rohit_portal/Port_Data/ " | sftp -q 10.188.24.100
